// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwkhsyricnczqzdnyyzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3a2hzeXJpY25jenF6ZG55eXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NjUzNTEsImV4cCI6MjA2NTU0MTM1MX0.QV-KoJ1inULTC_dh0I91VihidRLIqWb6SSs5hEEobWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);